name: Tinfoil Private Inference Build Action
description: Builds, attests, and publishes a private inference deployment.

author: Tinfoil

inputs:
  model:
    description: "OLLAMA model"
    required: true
  domain:
    description: "TLS domain"
    required: true
  github-token:
    description: "GitHub token"
    required: true

  cpus:
    description: "Number of vCPUs"
    default: "16"
  inference-image-release:
    description: "Inference release"
    default: "0.0.6"
  ovmf-release:
    description: "OVMF release"
    default: "0.0.2"

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create deployment manifest
      shell: bash
      run: |
        docker run --rm \
          -v $(pwd)/output:/output \
          -e INFERENCE_IMAGE_VERSION=${{ inputs.inference-image-release }} \
          -e OVMF_VERSION=${{ inputs.ovmf-release }} \
          -e CPUS=${{ inputs.cpus }} \
          -e DOMAIN=${{ inputs.domain }} \
          -e MODEL=${{ inputs.model }} \
          ghcr.io/tinfoilanalytics/pri-build-action:0.0.4

    - name: Hash deployment manifest
      shell: bash
      id: hash
      run: |
        echo stdout=sha256:$(sudo sha256sum output/tinfoil-deployment.json | cut -d ' ' -f 1 | sudo tee output/tinfoil.hash) >> $GITHUB_OUTPUT

    - name: Attest
      uses: actions/attest@v1
      id: attest
      with:
        subject-name: tinfoil-deployment.json
        subject-digest: ${{ steps.hash.outputs.stdout }}
        predicate-type: https://tinfoil.sh/predicate/snp-sev-guest/v1
        predicate-path: output/tinfoil-deployment.json

    - name: Generate release notes
      id: generate-release-notes
      shell: bash
      run: |
        RELEASE_NOTES=$(cat output/release.md)
        echo "release-notes<<EOF" >> "$GITHUB_OUTPUT"
        echo "${RELEASE_NOTES}" >> "$GITHUB_OUTPUT"
        echo "Digest: \`$(cat output/tinfoil.hash)\`" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          output/tinfoil-deployment.json
          output/tinfoil.hash
        body: ${{ steps.generate-release-notes.outputs.release-notes }}
